Update kalifull

diff --git a/KaliLinux/Chroot/kalifull b/KaliLinux/Chroot/kalifull
--- a/KaliLinux/Chroot/kalifull
+++ b/KaliLinux/Chroot/kalifull
@@ -1,3 +1,78 @@
+
+# VNC path
+DIR=chroot/kali-arm64/bin/vnc
+cat <<EOF > $DIR
+#!/bin/bash
+
+function start-kex() {
+    if [ ! -f ~/.vnc/passwd ]; then
+        passwd-kex
+    fi
+    USR=$(whoami)
+    if [ $USR == "root" ]; then
+        SCREEN=":2"
+    else
+        SCREEN=":1"
+    fi
+    export MOZ_FAKE_NO_SANDBOX=1; export HOME=${HOME}; export USER=${USR}; LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver $SCREEN >/dev/null 2>&1 </dev/null
+    starting_kex=1
+    return 0
+}
+
+function stop-kex() {
+    vncserver -kill :1 | sed s/"Xtigervnc"/"NetHunter VNC"/
+    vncserver -kill :2 | sed s/"Xtigervnc"/"NetHunter VNC"/
+    return 0
+}
+
+function passwd-kex() {
+    vncpasswd
+    return 0
+}
+
+function status-kex() {
+    sessions=$(vncserver -list | sed s/"TigerVNC"/"NetHunter VNC"/)
+    if [[ $sessions == *"590"* ]]; then
+        printf "\n${sessions}\n"
+        printf "\nOpen RealVNC client and to connect to 127.0.0.1:5901.\n\n"
+    else
+        if [ ! -z $starting_kex ]; then
+            printf '\nError starting the VNC server.\nPlease try "kali vnc kill" or restart your termux session.\n\n'
+        fi
+    fi
+    return 0
+}
+
+function kill-kex() {
+    pkill Xtigervnc
+    return $?
+}
+
+case $1 in
+    start)
+        start-kex
+        ;;
+    stop)
+        stop-kex
+        ;;
+    status)
+        status-kex
+        ;;
+    passwd)
+        passwd-kex
+        ;;
+    kill)
+        kill-kex
+        ;;
+    *)
+        stop-kex
+        start-kex
+        status-kex
+        ;;
+esac
+EOF
+
+# Nethunter path
 PATH=$PREFIX/bin/nethunter
 cat <<EOF > $PATH
 #!/data/data/com.termux/files/usr/bin/bash -e
